plot bar chart based on calculated mean
Rostlab/JS18_ProjectB_Group3 pull request #58
Opened 2018-03-25 13:23 UTC by AhmetTanakol

Calculate average of an axis and draw the new data as bar chart

Fix #19

2018-03-27 00:23 UTC, syxolk requested changes

2018-03-27 00:23 UTC, syxolk commented on app/assets/scripts/modules/calculateAverage.js
> +            numbers[value]['count'] += 1;
Same code duplication here.

2018-03-27 00:24 UTC, syxolk commented on app/assets/scripts/modules/calculateAverage.js
> +            numbers[value]['count'] += 1;
Here's a lot a duplicated code. You can move this out of the if/else:
```
numbers[value]['count'] += 1;
numbers[value]['sum'] += d.y[index];
```

2018-03-27 12:43 UTC, AhmetTanakol commented
updated

2018-03-28 10:18 UTC, syxolk approved these changes

2018-03-28 10:31 UTC, merged